### ISSUE TITLE
Train on custom dataset using crops

### ISSUE THREAD

**Issue by raphaelsulzer** [autonomousvision/convolutional_occupancy_networks#41]
Hi,

I have successfully trained ConvONet on my own object datasets before with nice results!
I have used the sample_mesh.py script from ONet to generate `pointcloud.npz` and `points.npz` (occupancy points) files.

I would now like to train the network to reconstruct very large scenes, for which I have ground truth meshes for some of them. How do I go about this?

Can I simply provide one `points.npz` and `pointcloud.npz` file per scene? How do I make sure to have enough occupancy samples per crop? Should I simply make sure to have 100k occupancy points per crop defined by `voxel_size * resolution`?
Or do I need to do the cropping myself?

Kind regards

**Comment by hahahahahahahap** [comment]
Hi, 
 
I met  the same problem. 
```
Error occured when loading field inputs of model building
Traceback (most recent call last):
  File "generate.py", line 75, in <module>
    for it, data in enumerate(tqdm(test_loader)):
  File "/home/cxj/anaconda3/envs/conv_onet1/lib/python3.6/site-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/home/cxj/anaconda3/envs/conv_onet1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/cxj/anaconda3/envs/conv_onet1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/cxj/anaconda3/envs/conv_onet1/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/cxj/anaconda3/envs/conv_onet1/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 86, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>
```
I used sample_mesh.py to create  pointcloud.npz file. 

Could you give me a hint ?
